### ISSUE TITLE
OSM-POI: SIGKILL when processing OSM download

### ISSUE THREAD

**Issue by Rikuoja** [kuwala-io/kuwala#33] opened 2021-06-10 12:20 UTC
Thanks everybody again for this tool! Out of the box, I couldn't get OSM data processing to work either. The download works fine, but the processing step most likely causes Node to run out of memory or something similar:
```
[1] Existing download
[2] New download
[0] Cancel

Do you want to make a new download? [1, 2, 0]: 1

[1] europe
[0] Cancel

Which region are you interested in? [1/0]: 1

[1] finland-latest.osm.pbf
[0] Cancel

Which region are you interested in? [1/0]: 1
Running: 0s - 0 objects added
Running: 7m47s - 233807 objects addednpm ERR! path /opt/app
npm ERR! command failed
npm ERR! signal SIGKILL
npm ERR! command sh -c NODE_ENV=local node --max-old-space-size=8192 src/data/main.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-10T11_17_00_519Z-debug.log
ERROR: 1
```

**Comment by mattigrthr** [comment] 2021-06-10 17:23
Hey @Rikuoja! I just ran it for Finland using Docker on my local machine (8GB RAM, i5), and it completed the processing successfully.
```
[z] luxembourg
[0] Next page

Which region are you interested in? [1...9, a...z, 0]: j
Running: 1h1m - 2363368 objects added
```
My first best guess is also that it ran out of memory in your case. How many resources did you attribute to Docker? This is my configuration:

<img width="1246" alt="image" src="https://user-images.githubusercontent.com/28758040/121569085-b5a22a00-ca20-11eb-86ac-466e867723b6.png">

Could you try to add more resources to Docker if you have less atm? Or you could try it with a small country first, e.g., Malta, to see whether it's really about the memory.

Otherwise, please retrieve the logs as suggested in the error message under `npm ERR!     /root/.npm/_logs/2021-06-10T11_17_00_519Z-debug.log`. Unfortunately, just from `SIGKILL` it's hard to tell what exactly the issue is.

**Comment by mattigrthr** [comment] 2021-11-23 11:24
Closing this for now. If anybody runs into the same issue, feel free to reopen.

**Closed by mattigrthr** 2021-11-23 11:24 UTC
Labels: bug, pipeline, pipeline/osm-poi
